# Generated by Django 4.1.7 on 2023-03-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresscontent',
            unique_together={('ticket_number', 'date', 'description')},
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.progressreport')),
            ],
            options={
                'unique_together': {('team_number', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='Completes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collaborator')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.progressreport')),
            ],
            options={
                'unique_together': {('collaborator_id', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='Assigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.admin')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('team_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'unique_together': {('team_number', 'admin_id', 'project_id')},
            },
        ),
    ]
