# Generated by Django 4.1.7 on 2023-03-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_progresscontent_unique_together_workson_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completes',
            new_name='Complete',
        ),
    ]
