# Generated by Django 4.1.7 on 2023-03-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_completes_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigns',
            new_name='Assign',
        ),
    ]
