# Generated by Django 4.1.7 on 2023-03-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_assigns_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='team_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
